export const DEFAULT_SETTINGS = {
  enabled: true,
  defaultCategory: "happy",
  sendMode: "append",
  matchMode: "tag_and_keyword",
  memeTriggerProbability: 100,
  randomPick: true,
  maxImagesPerReply: 1,
  replySuffixEnabled: false,
  streamingCompatibility: true,
  categories: [
    { label: "angry", description: "Angry, annoyed, or intense disagreement.", dir: "memes/angry", keywords: ["angry", "生气", "愤怒", "气死", "火大", "炸毛"] },
    { label: "baka", description: "Calling someone silly or foolish in a playful way.", dir: "memes/baka", keywords: ["baka", "笨蛋", "呆瓜", "白痴", "蠢", "傻瓜"] },
    { label: "color", description: "Flirty, spicy, or blush-heavy reactions.", dir: "memes/color", keywords: ["color", "涩涩", "色", "撩", "心动", "上头"] },
    { label: "confused", description: "Confused, puzzled, or questioning mood.", dir: "memes/confused", keywords: ["confused", "疑惑", "困惑", "迷惑", "不懂", "问号"] },
    { label: "cpu", description: "Thinking hard, overloaded, or brain-burning reactions.", dir: "memes/cpu", keywords: ["cpu", "烧脑", "思考", "过载", "算不明白", "头大"] },
    { label: "fool", description: "Calling out nonsense or ridiculous behavior.", dir: "memes/fool", keywords: ["fool", "离谱", "逆天", "无语", "傻眼", "蠢"] },
    { label: "givemoney", description: "Money, rewards, sponsor jokes, or asking to pay.", dir: "memes/givemoney", keywords: ["givemoney", "给钱", "打钱", "红包", "转账", "赞助"] },
    { label: "happy", description: "Happy, cheerful, praise, or excited positive mood.", dir: "memes/happy", keywords: ["happy", "开心", "高兴", "快乐", "嘿嘿", "哈哈"] },
    { label: "like", description: "Approval, like, support, or admiration.", dir: "memes/like", keywords: ["like", "喜欢", "点赞", "认可", "支持", "不错"] },
    { label: "meow", description: "Cat-like, cute, or meow mood.", dir: "memes/meow", keywords: ["meow", "喵", "猫猫", "猫咪", "可爱猫", "咪"] },
    { label: "morning", description: "Good morning and wake-up reactions.", dir: "memes/morning", keywords: ["morning", "早安", "早上好", "起床", "清晨", "早呀"] },
    { label: "reply", description: "Acknowledgement and reply receipt.", dir: "memes/reply", keywords: ["reply", "收到", "收到啦", "回你", "ok", "明白"] },
    { label: "sad", description: "Sad, hurt, crying, or disappointed mood.", dir: "memes/sad", keywords: ["sad", "难过", "伤心", "委屈", "哭", "沮丧"] },
    { label: "see", description: "Watching, peeking, observing, or checking.", dir: "memes/see", keywords: ["see", "看", "看看", "瞄", "观察", "围观"] },
    { label: "shy", description: "Shy, embarrassed, or blushing reaction.", dir: "memes/shy", keywords: ["shy", "害羞", "不好意思", "羞涩", "脸红", "扭捏"] },
    { label: "sigh", description: "Sigh, helplessness, or emotional fatigue.", dir: "memes/sigh", keywords: ["sigh", "唉", "叹气", "无奈", "心累", "服了"] },
    { label: "sleep", description: "Sleepy, tired, or good night mood.", dir: "memes/sleep", keywords: ["sleep", "困", "睡", "晚安", "休息", "睡觉"] },
    { label: "surprised", description: "Shocked, surprised, or jaw-dropping reaction.", dir: "memes/surprised", keywords: ["surprised", "惊讶", "震惊", "哇", "啊", "不可思议"] },
    { label: "work", description: "Work, overtime, labor, or grind mood.", dir: "memes/work", keywords: ["work", "工作", "上班", "加班", "干活", "搬砖"] }
  ],
  keywords: {
    angry: ["angry", "生气", "愤怒", "气死", "火大", "炸毛"],
    baka: ["baka", "笨蛋", "呆瓜", "白痴", "蠢", "傻瓜"],
    color: ["color", "涩涩", "色", "撩", "心动", "上头"],
    confused: ["confused", "疑惑", "困惑", "迷惑", "不懂", "问号"],
    cpu: ["cpu", "烧脑", "思考", "过载", "算不明白", "头大"],
    fool: ["fool", "离谱", "逆天", "无语", "傻眼", "蠢"],
    givemoney: ["givemoney", "给钱", "打钱", "红包", "转账", "赞助"],
    happy: ["happy", "开心", "高兴", "快乐", "嘿嘿", "哈哈"],
    like: ["like", "喜欢", "点赞", "认可", "支持", "不错"],
    meow: ["meow", "喵", "猫猫", "猫咪", "可爱猫", "咪"],
    morning: ["morning", "早安", "早上好", "起床", "清晨", "早呀"],
    reply: ["reply", "收到", "收到啦", "回你", "ok", "明白"],
    sad: ["sad", "难过", "伤心", "委屈", "哭", "沮丧"],
    see: ["see", "看", "看看", "瞄", "观察", "围观"],
    shy: ["shy", "害羞", "不好意思", "羞涩", "脸红", "扭捏"],
    sigh: ["sigh", "唉", "叹气", "无奈", "心累", "服了"],
    sleep: ["sleep", "困", "睡", "晚安", "休息", "睡觉"],
    surprised: ["surprised", "惊讶", "震惊", "哇", "啊", "不可思议"],
    work: ["work", "工作", "上班", "加班", "干活", "搬砖"]
  }
};
